### ISSUE TITLE
4.02 Port - Request for clarification

### ISSUE THREAD

**Issue by vrotaru** [ftovagliari/ocamleditor-mingw#1]
Hi, Francesco, are interested in a port to 4.02 version of OCaml, and maybe higher version?

I'm asking because after some changes I have `ocamleditor` running with the `4.02.3` version of Ocaml locally. 

A lot of changes are just placeholder marked with **TODO** but it works.
Some more details from `opam list`

```txt
lablgtk             2.18.5      OCaml interface to GTK+
ocaml-base-compiler 4.02.3      Official 4.02.3 release
ocamlfind           1.8.1       A library manager for OCaml
ocp-indent          1.5         A simple tool to indent OCaml programs
xml-light           2.4         Xml-Light is a minimal XML parser & printer for OCaml
```
Let me know if you are interested.

**Comment by vrotaru** [comment]
![image](https://user-images.githubusercontent.com/246236/71534660-e8c62b80-2908-11ea-9ab8-488aa388cbf9.png)

**Comment by ftovagliari** [comment]
Hi Vasile, although it is no longer possible for me to continue developing ocamleditor, I am still interested in your porting. Is it publicly available? 
Thank you.
Best regards,
Francesco

**Comment by vrotaru** [comment]
Hi. Not yet. I guess the best is to just clone the project the changes. 

I'll let you know when it is done. Thanks for quick reply.

**Comment by vrotaru** [comment]
So you can have a look at the [4.02.3-port](https://github.com/vrotaru/ocamleditor/tree/4.02.3-port) branch.

I've "corrupted" your `build.ml` generation so that it now only inside the `ocamleditor` source tree. I understand the motivation and agree with it, but the current version helped me start with the port.

**Comment by ftovagliari** [comment]
Ok, thanks for letting me know.
